<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXGc3e4e\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXGc3e4e/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXGc3e4e.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXGc3e4e\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXGc3e4e\App_KernelDevDebugContainer([
    'container.build_hash' => 'XGc3e4e',
    'container.build_id' => 'f84a070b',
    'container.build_time' => 1727787036,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXGc3e4e');
