<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGzJsdOP\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGzJsdOP/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGzJsdOP.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGzJsdOP\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGzJsdOP\App_KernelDevDebugContainer([
    'container.build_hash' => 'GzJsdOP',
    'container.build_id' => '99825944',
    'container.build_time' => 1727853627,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGzJsdOP');
