<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIkxlHkx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIkxlHkx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIkxlHkx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIkxlHkx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIkxlHkx\App_KernelDevDebugContainer([
    'container.build_hash' => 'IkxlHkx',
    'container.build_id' => '9d4e7a96',
    'container.build_time' => 1727854850,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIkxlHkx');
